name: Debug and Deploy React App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  debug-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Repository Contents
        run: |
          echo "REPOSITORY CONTENTS:"
          ls -la
          echo "-----------------"
          echo "PACKAGE.JSON CONTENT:"
          cat package.json || echo "package.json not found!"
          echo "-----------------"
          echo "SRC DIRECTORY:"
          ls -la src || echo "src directory not found!"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
        continue-on-error: true

      - name: Build React App
        run: |
          echo "Building React app..."
          npm run build
        continue-on-error: true

      - name: Check Build Results
        run: |
          echo "Checking build results..."
          ls -la build || echo "Build directory not found!"
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: success()
        with:
          folder: build
